// TO BE CREATED
//
// USERS CAN CREATE INVITATIONS, THAT EITHER HAVE FIXEDC OR DYNAMIC UNITS
// - FIXED UNITS MEANS THAT EVERYONE THAT IS INVITED GETS THE EXACT SAME UNITS.
//   THIS MAKES SENSE FOR EXPERIMENTS OR SURVEYS, AND CAN ALSO BE USED TO MANUALLY
//   DIVIDE UP UNITS OVER FIXED CODERS (I.E. EVERY CODER A UNIQUE LINK)
// - DYNAMIC UNITS MEANS THAT EVERYONE THAT IS INVITED GETS A UNIQUE SET OF UNITS.
//
//
// FOR FIXED UNITS, WE PROVIDE OPTION TO DISTRIBUTE UNITS OVER SETS AUTOMATIACLLY OR MANUALLY
// AUTOMATICALLY COULD FOR INSTANCE BE: DIVIDE EQUALLY WITH X OVERLAP UNITS
// MANUAL MODE MEANS THEY CAN MANUALLY SELECT WHICH UNITS TO GO TO WHICH SET/INVITATION AND
// IN WHAT ORDER.
// WE NEED TO PROVIDE WARNING WHEN THERE ARE INVITATIONS WITHOUT ANY UNITS (E.G. IF SOMEONE
// ADDS A SET WHILE IN MANUAL MODE AND FORGETS TO ADD UNITS)

// PROVIDE COMMON MODES THAT CORRESPOND TO SETS/INVITATIONS
// - EXPERIMENT WITH IDENTICAL UNITS (CAN MANIPULATE PRESENTATION IN CODEBOOK)
//
